### PR TITLE
Add date too console.

### PR DESCRIPTION
**Pull request by whitewillem**
Level 30 accounts last longer than 24hours now. This helps to see how long.

Tested for a few hours. Looks good too me.

### CODE REVIEW

**Comment by tomballgithub** [comment]
Can you post a photo of what the changes look like?

**Comment by whitewillem** [comment]
tvybmojks6izsgmw4ri8fa

**Comment by rlodev67** [comment]
Could be better to display the date only for starter and not for last encounter

**Comment by whitewillem** [comment]
To be honest i don't know how. If thats required to get this merged i would need some help. Or (a lot) of time to learn python better.

**Comment by tomballgithub** [comment]
He is saying that you added it for both columns and maybe we shouldn't on the 2nd.  I thought the same thing until I realized that adding it for last encounter doesn't actually make the screen display wider.

**Pull request merged**
