### PR TITLE
Configure encounter action delay

### PR DESCRIPTION
**Pull request by ngovil21**
This PR will override the default action delay in Mr. Mime, allowing for increased encounters per hour. In testing, values around 0.5 maxes out individual scouts abilities for up to 4000 encounters/hr. Has not affected current ban rates or caused increased shadowbans. May occassionally give Niantic throttling exceptions, which cause a 5 second wait.

### CODE REVIEW

**Comment by tomballgithub** [comment]
Wow!  I need to test this

**Comment by tomballgithub** [comment]
I don't think you need the 2.25 default in both config.py and scout.py.  Only have it in config.py

**Comment by tomballgithub** [comment]
4K per hr with 0.50.  
image

**Comment by tomballgithub** [comment]
6K per hr with 0.50 and multiplier of 2
image

**Comment by tomballgithub** [comment]
What is the default in current code?  Is it 2.25 like the default here?

**Comment by ngovil21** [comment]
Yes this value is 2.25 by default in Mr. Mime. We override the method to change the value.

**Comment by ngovil21** [comment]
No it definitely could be coded into Mr. Mime, in fact it's probably better to do it that way so if the code is updated it is still there.

I just don't usually look at Mr. Mime code very often and I feel the configuration can get lost there. I probably don't even know all the options that are there.

**Comment by tomballgithub** [comment]
I agree that this should be updated in Mr Mime and not here and the configuration file should be used.

**Comment by tomballgithub** [comment]
It does seem more appropriate to make the item configurable within Mr Mime using the config file mechanism.  Then it can be used by any/all tools and not just PGScout

**Comment by ngovil21** [comment]
Agreed.

**Comment by TheQL** [comment]
So, configurable via both methods, mrmime_config.json for all tools and add it to PGScout config.ini for additional convenience?

**Comment by tomballgithub** [comment]
Let's keep this open for the moment because I have learned the hard way that once closed it can be hard to reopen.

**Comment by tomballgithub** [comment]
@ngovil21 Are you going to update mrmime instead?

**Comment by ngovil21** [comment]
No just in mrmime_config.json.

**Comment by ngovil21** [comment]
Ya I closed it because I was going to submit  a PR to MrMime, later today when I get back to a computer.

**Comment by ngovil21** [comment]
See https://github.com/SenorKarlos/MrMime/pull/3

**Pull request closed without merging**
